### ISSUE TITLE
Updating Title/Date/Time on Meetup

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-group-docs#24]
What do user group leaders need to do when they change the title and/or date/time of a event on Meetup? What is the best way to notify a volunteer that the Google calendar and GitHub issues (and possibly the SS46 booking) need to be updated?

**Comment by kacollins** [comment]
This would probably be the best place to put the answer to this question: https://github.com/techlahoma/user-group-docs/blob/master/Meetup-Events.md

I can do that if I know what it is. :)

**Comment by carmalou** [comment]
this is complete
