### ISSUE TITLE
Food/Drink Reimbursement Instructions

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-group-docs#8]
Add a markdown file for food/drink reimbursement instructions 
https://github.com/techlahoma/user-groups/wiki/Food-and-Drinks
https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement

**Comment by nexocentric** [comment]
Okay you assign me to this one?

**Comment by nexocentric** [comment]
This was closed by PR #20 .
